name: wethr
version: latest
version-script: git -C parts/wethr/build describe --tags
summary: Command line weather tool.
description: |
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

grade: stable
confinement: strict

apps:
  wethr:
    command: wethr
    plugs:
      - network

parts:
  wethr:
    plugin: nodejs
    source: https://github.com/twobucks/wethr.git
    source-type: git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info wethr | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
    build-packages:
      - git
      - sed
